# Generated by Django 5.1.7 on 2025-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
